name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest   # The environment to run on

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "No specific language set up yet."
          echo "You can add setup steps here (like Node, Python, Java, etc.)"

      - name: Run build/test steps
        run: |
          echo "Replace this with your build commands"
          echo "For example: npm install && npm test OR python -m unittest"

